server/NHSApp/MetabolicApp/urls.py
from django.conf.urls import url, include
from rest_framework.routers import DefaultRouter
from rest_framework_jwt.views import obtain_jwt_token

import MetabolicApp.html_views.inboxViews
import MetabolicApp.html_views.testResultViews
import MetabolicApp.html_views.loginViews
import MetabolicApp.views
from rest_framework.authtoken import views

app_name = 'Metabolic_App'


urlpatterns = [
    url(r'^login/', MetabolicApp.html_views.loginViews.loginView, name='login'),
    url(r'^logout/$', MetabolicApp.html_views.loginViews.logoutView, name='logout'),
    url(r'^home/$', MetabolicApp.views.homeView, name='home'),


    url(r'^view-inbox/$', MetabolicApp.html_views.inboxViews.clinicianInboxView, name='view_inbox'),
    url(r'^view-inbox/request/(?P<inbox_entry_id>[0-9]+)/$', MetabolicApp.html_views.inboxViews.requestEntryView,name='view_inbox_request'),
    url(r'^view-inbox/submission/(?P<inbox_entry_id>[0-9]+)/$', MetabolicApp.html_views.inboxViews.submissionEntryView, name='view_inbox_submission'),

    url(r'^view-patients/$', MetabolicApp.html_views.testResultViews.patientSelectView, name='view_patients'),
    url(r'^view-patients/patient/(?P<patient_id>[0-9]+)/$', MetabolicApp.html_views.testResultViews.patientView, name='view_patient'),
    url(r'^view-patients/patient/(?P<patient_id>[0-9]+)/trends/(?P<option>[a-z]+)/$',
        MetabolicApp.html_views.testResultViews.selectTrendTypeView, name='select_trends'),
    url(r'^view-patients/patient/(?P<patient_id>[0-9]+)/trends/view/(?P<test_type>[A-Z]+)/$',
        MetabolicApp.html_views.testResultViews.viewPatientDataView, name='view_patient_data'),
    url(r'^view-patients/patient/(?P<patient_id>[0-9]+)/trends/input/(?P<test_type>[A-Z]+)/$',
        MetabolicApp.html_views.testResultViews.inputPatientDataView, name='input_patient_data'),
    url(r'^test-result/$', MetabolicApp.views.getTestResults),
    url(r'^api-login/$', MetabolicApp.views.obtain_jwt_token)
]

server/NHSApp/NHSApp/urls.py
from django.conf.urls import url, include

#from django.contrib import admin

urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^', include('MetabolicApp.urls')),
    #url(r'^rest-auth/', include('rest_auth.urls'))
]

server/NHSApp/MetabolicApp/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import AbstractUser, PermissionsMixin
from django.db import models
from django.db.models.signals import post_save
from rest_framework.authtoken.models import Token
from django.dispatch import receiver
# Create your models here.
from NHSApp import settings


class Clinician(models.Model):

    def __str__(self):
        return self.username

    def is_authenticated(self):
        return True

    username = models.CharField(max_length=40, null=False, unique=True)
    full_name = models.CharField(max_length=40, null=False)
    password_hash = models.TextField(null=False)
    password_salt = models.CharField(max_length=255)
    GMC_no = models.CharField(max_length=40, null=False, unique=True)
    practice_no =  models.CharField(max_length=40, null=False, unique=True)
    last_login = models.DateTimeField(null=True, blank=False)
    date_created = models.DateTimeField(auto_now_add=True)

class Patient(models.Model):

    def __str__(self):
        return self.email

    @property
    def is_authenticated(self):
        return True

    @staticmethod
    def getAuthorizedPatients(clinician_id):
        return Patient.objects.filter(clinician_id=clinician_id)


    @staticmethod
    def checkDataAccessRequest(patient_id, clinician_id):
        return Patient.objects.filter(clinician_id=clinician_id, id=patient_id.id).exists()

    @staticmethod
    def hasClinician(patient_id):
        return Patient.objects.get(id=patient_id.id).clinician_id is not None

    username = models.CharField(max_length=40, null=False, unique=True)
    email = models.CharField(max_length=40, null=True)
    first_name = models.CharField(max_length=40, null=False)
    last_name = models.CharField(max_length=40, null=False)
    password_hash = models.TextField(null=False)
    password_salt = models.CharField(max_length=255)
    DoB = models.DateField(null=False)
    NHS_no = models.CharField(max_length=40, null=False, unique=True)
    clinician_id = models.ForeignKey(Clinician,models.SET_NULL, null=True, blank=True)
    date_created =models.DateTimeField(auto_now_add=True)
    access_token = models.TextField(max_length=255, null=True)
    access_token_created_on = models.DateTimeField(null=True)
    is_active = models.BooleanField(('active'), default=True)
    is_anonymous = models.BooleanField(('active'), default=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['first_name','last_name','DoB', 'NHS_no']



class Inbox(models.Model):

    def __str__(self):
        return 'InboxEntry: '+ self.patient_id.username + ' ' + self.clinician_id.username

    @staticmethod
    def hasPendingRequest(patient_id):
        pass     #TODO(Kiran): Implement methods

    @staticmethod
    def getPendingRequest(patient_id):
        pass     #TODO(Kiran): Implement methods

    @staticmethod
    def getClinicianInboxEntries(clinician_id):
        entries = Inbox.objects.filter(clinician_id=clinician_id)
        result = []
        for entry in entries:
            patient = entry.patient_id
            result_entry = {}
            result_entry['id'] = patient.id
            result_entry['name'] = patient.first_name + " " + patient.last_name
            result_entry['type'] = entry.entry_type
            result_entry['age'] = entry.date_created.ctime()
            result.append(result_entry)
        return result

    @staticmethod
    def authorizedViewRequest(clinician_id, inbox_entry_id):
        return Inbox.objects.filter(clinician_id=clinician_id, id=inbox_entry_id).exists()


    ENTRY_TYPES = (('REQUEST', 'request'),('SUBMISSION','submission'))
    # id = models.AutoField(primary_key=True, unique=True, blank=True, null=False)
    clinician_id = models.ForeignKey(Clinician,models.CASCADE,null=False)
    patient_id = models.ForeignKey(Patient,models.CASCADE,null=False)
    entry_type = models.CharField(max_length=10,choices=ENTRY_TYPES, null=False, blank=False)
    message = models.TextField(null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)

class TestResult(models.Model):

    def __str__(self):
        return 'TestEntry: '+' '.join((self.patient_id, self.clinician_id))

    @staticmethod
    def getTestResultsForPatient(patient_id, test_type):
        return TestResult.objects.filter(patient_id=patient_id, test_type=test_type)
        responses = []

        for result in results:
            response = {}
            response['date_created'] = result.date_created
            response['message'] = result.message
            response['data'] = result.test_data
            response['next_test'] = result.next_test



    @staticmethod
    def getAllTestResultsForPatient(patient_id):
        return TestResult.objects.filter(patient_id=patient_id)

    @staticmethod
    def isValidType(test_type):
        return any([test_type == test[0] for test in TestResult.ENTRY_TYPES])

    @staticmethod
    def getReadableTypeName(test_type):
        return [test[1] for test in TestResult.ENTRY_TYPES if test_type == test[0]][0]

    ENTRY_TYPES = (('CHOLESTEROL', 'Fasting cholesterol'),('LIPIDS','Lipids'), ('PROLACTIN','Prolactin'), ('RENAL','Renal_Functions'),
                   ('BLOOD','Blood_pressure'), ('ECG','ECGs'), ('BMI','BMI'), ('FBSUGAR','Fasting_blood_sugar'), ('HBA1C','HbA1c'),
                   ('LIVER','Liver_function'))

    test_type = models.CharField(max_length=15,choices=ENTRY_TYPES, null=False, blank=False)
    test_data = models.FileField(null=False)
    clinician_id = models.ForeignKey(Clinician,models.ProtectedError,null=False)
    patient_id = models.ForeignKey(Patient, models.ProtectedError, null=False)
    next_test = models.DateField(null=False, blank=True)
    message = models.TextField(null=False, blank=False)
    date_created = models.DateTimeField(auto_now_add=True)

@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwarg):
    if created:
        Token.objects.create(user=instance)

server/NHSApp/MetabolicApp/forms.py
from django.forms import forms, ChoiceField, Select, ModelForm

from MetabolicApp.models import TestResult


class TestResultSelectForm(forms.Form):
    choices = TestResult.ENTRY_TYPES
    select = ChoiceField(widget=Select, choices=choices)

class TestResultInsertForm(ModelForm):
    class Meta:
        model = TestResult
        fields = ['test_data', 'message', 'next_test']

server/NHSApp/MetabolicApp/views.py
import datetime
import jws as jws
import rest_framework
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse, exceptions
from django.views.decorators.csrf import csrf_exempt
from rest_framework import generics
from rest_framework import mixins
from rest_framework import permissions
from rest_framework import status
from rest_framework import viewsets
from rest_framework.authtoken.models import Token
from rest_framework.decorators import api_view, permission_classes
from rest_framework.renderers import JSONRenderer
from rest_framework.response import Response
from rest_framework.views import APIView
from MetabolicApp.auth import PatientBackend, JWTAuthentication

from rest_framework import exceptions
import MetabolicApp
from MetabolicApp.models import TestResult, Patient
from MetabolicApp.rest_api.serializers import TestResultSerializer, PatientSerializer


@login_required(login_url="/login/")
def homeView(request):
    options = [{'name':'View Patient Options', 'url': reverse('Metabolic_App:view_patients')},
               {'name':'View personal Inbox', 'url' : reverse('Metabolic_App:view_inbox')},
               ]
    return render(request, 'MetabolicApp/home.html', {'options': options})


class PatientList(mixins.ListModelMixin, mixins.CreateModelMixin,generics.GenericAPIView):
    queryset = Patient.objects.all()
    serializer_class = PatientSerializer

    def get(self, request, *args, **kwargs):
        return self.list(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        return self.create(request, *args, **kwargs)

class PatientLogin(APIView):
    permission_classes = (permissions.IsAuthenticated,)

    def get(self, request, format=None):
        patients = Patient.objects.all()

def obtain_jwt_token(request):
    try:
        username = request.POST['username']
        password = request.POST['password']
    except KeyError:
        raise rest_framework.exceptions.NotAcceptable
    try:
        user = PatientBackend().authenticate(username=username, password=password)
    except:
        raise rest_framework.exceptions.AuthenticationFailed
    expiry = datetime.date.today() + datetime.timedelta(days=30)
    token = jws.sign({'username':user.username, 'expiry':expiry}, 'seKre8', algorithm='HS256')
    return HttpResponse(token)

@login_required(login_url='/api-login/')
def getTestResults(request):
    for i in request.POST.items():
        print(i)

server/NHSApp/templates/MetabolicApp/base.html
<html>
<head>
    <title>
        {% block title %}

        {% endblock %}
    </title>
</head>
<body>
<a href="{% url 'Metabolic_App:home' %}"><button type="button">Home page</button></a>
<a href="{% url 'Metabolic_App:logout' %}"><button type="button">Logout</button></a>
<br/>
{% block content %}


{% endblock %}
</body>


</html>

server/NHSApp/templates/MetabolicApp/error.html
{% extends 'MetabolicApp/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<h2>An unknown error occurred, please contact sysadmin.</h2>
    <a href="/home">Go Back to Home</a>
{% endblock %}

server/NHSApp/templates/MetabolicApp/home.html
{% extends 'MetabolicApp/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <ul>
{% for option in options %}

    <li><a href="{{ option.url }}">{{ option.name }}</a></li>

{% endfor %}
    </ul>
{% endblock %}

server/NHSApp/templates/MetabolicApp/input_patient_results.html
{% extends 'MetabolicApp/base.html' %}

{% block title %}Input Test Result - Metabolic App{% endblock %}

{% block content %}
    <h3>Selecting {{ type }} Trend for Patient - {{ patient.first_name }} {{ patient.last_name }}</h3>
    <ul>
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
    </form>
    </ul>
{% endblock %}

server/NHSApp/templates/MetabolicApp/select_trend.html
{% extends 'MetabolicApp/base.html' %}

{% block title %}View Patient{% endblock %}

{% block content %}
    <h3>Selecting Trend for Patient - {{ patient.first_name }} {{ patient.last_name }}</h3>
    <form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
    </form>
{% endblock %}

server/NHSApp/templates/MetabolicApp/unauthorized_request.html
{% extends 'MetabolicApp/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<h2>You are not authorized to view this content.</h2>
    <a href="/home">Go Back to Home</a>
{% endblock %}

server/NHSApp/templates/MetabolicApp/view_patient.html
{% extends 'MetabolicApp/base.html' %}

{% block title %}View Patient{% endblock %}

{% block content %}
    <h3>Viewing Patient - {{ patient.first_name }} {{ patient.last_name }}</h3>
    <ul>
    <li>
        <a href="{% url 'Metabolic_App:select_trends' patient.id 'view'%}">View Test Data for Patient</a>
        <a href="{% url 'Metabolic_App:select_trends' patient.id 'input'%}">Input Test Data for Patient </a>
    </li>
    </ul>
{% endblock %}

server/NHSApp/templates/MetabolicApp/view_patient_list.html
{% extends 'MetabolicApp/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <ul>
{% for patient in patients %}
    <li>
        <a href="{% url 'Metabolic_App:view_patient' patient.id %}">{{ patient.first_name }} {{ patient.last_name }}</a>
    </li>
{% endfor %}
    </ul>
{% endblock %}

server/NHSApp/templates/MetabolicApp/view_patient_results.html
{% extends 'MetabolicApp/base.html' %}
{% load custom_filters %}

{% block title %}View Patient{% endblock %}

{% block content %}
    <h3>Viewing {{ type }} Trends for Patient - {{ patient.first_name }} {{ patient.last_name }}</h3>
    <table>
    <tr>
        <th>Date Created</th>
        <th>Test Result</th>
        <th>Clinician Message</th>
        <th>Clinician</th>
        <th>Recommended Next Test</th>
    </tr>
    {% for result in results %}
        <td>{{ result.date_created }}</td>
        <td>{{ result.test_data|read }}</td>
        <td>{{ result.message }}</td>
        <td>{{ result.clinician_id.full_name }}, {{ result.clinician_id.GMC_no }}</td>
        <td>{{ result.next_test }}</td>
    {% endfor %}
    </table>
{% endblock %}